### PR TITLE
Update to moviepy 1.0.1

### PR DESCRIPTION
**Pull request by mdraw**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mdraw** [comment]
@conda-forge-admin, please restart ci

**Comment by mdraw** [comment]
@jakirkham, can you please review this PR if you have time?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart ci.

**Comment by jakirkham** [comment]
Thanks @mdraw! Sorry for the delay!

**Pull request merged**
