### PR TITLE
Fix the `unpin_decorators.patch` file.

### LINKED ISSUE #16: V1.0.3 on conda-forge is broken
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The function "use_clip_fps_by_default " in decorators.py is broken. It gives the error "NameError("name 'func' is not defined")".  In the sources of 1.0.3 from github (or pypi) the function looks different, so I suspect there must be an issue in the build/packaging process.

```shell
@decorator.decorator
def use_clip_fps_by_default(f, clip, *a, **k):
    """ Will use clip.fps if no fps=... is provided in **k """
    
    def fun(fps):
        if fps is not None:
            return fps
        elif getattr(clip, 'fps', None):
            return clip.fps
        raise AttributeError("No 'fps' (frames per second) attribute specified"
                " for function %s and the clip has no 'fps' attribute. Either"
                " provide e.g. fps=24 in the arguments of the function, or define"
                " the clip's fps with `clip.fps=24`" % f.__name__)


    names = inspect.getfullargspec(func).args[1:]
    
    new_a = [fun(arg) if (name=='fps') else arg
             for (arg, name) in zip(a, names)]
    new_kw = {k: fun(v) if k=='fps' else v
             for (k,v) in k.items()}

    return f(clip, *new_a, **new_kw)
```

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

### PR DESCRIPTION
**Pull request by alanhdu**
Closes #16

### CODE REVIEW

**Comment by alanhdu** [comment]
cc @hmaarrfk, since I think you also seem to be a maintainer / have merge-access?

(apologies for the ping if you don't).

**Comment by alanhdu** [comment]
cc @jakirkham @hmaarrfk -- is there anything I can do here to help get this merged in? Without this, the current version of moviepy on conda is broken.

**Comment by alanhdu** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Thanks Alan! 🙏

It is worth noting that this is a Python 3 only package now, but AIUI this patch was for Python 2. Am wondering should we just drop the patch? Or is it still needed for some reason?

**Comment by alanhdu** [comment]
> It is worth noting that this is a Python 3 only package now, but AIUI this patch was for Python 2. Am wondering should we just drop the patch? Or is it still needed for some reason?

I'm not an expert here, but IIUC ths patch correctly it's meant to allow moviepy to use `decorator=5` (this seems to be a port of https://github.com/Zulko/moviepy/pull/1565) -- I think that Python 2 builds are already skipped (see https://github.com/conda-forge/moviepy-feedstock/commit/feffd3f051d6b5cfb3fb6be9b1583ca0436f4379 where this was added), so I'm not sure we can drop the patch.

(I think the "root" problem is that moviepy hasn't cut a release in almost 2 years now, which is why some of the dependencies needed to get updated).

**Comment by jakirkham** [comment]
Gotcha. Thanks for the context! 🙏

Yeah it seems they are working on it ( https://github.com/Zulko/moviepy/issues/1089 ), but it is a big release, which would take time to get out.

**Pull request merged**
